use crate::board::{Board, BoardKind, Item, ItemKind};
use crate::uniqueness::is_unique;
use cspuz_rs_puzzles::puzzles::masyu;

pub fn solve(url: &str) -> Result<Board, &'static str> {
    use masyu::MasyuClue;

    let problem = masyu::deserialize_problem(url).ok_or("invalid url")?;
    let is_line = masyu::solve_masyu(&problem).ok_or("no answer")?;

    let height = problem.len();
    let width = problem[0].len();
    let mut board = Board::new(BoardKind::Grid, height, width, is_unique(&is_line));

    for y in 0..height {
        for x in 0..width {
            match problem[y][x] {
                MasyuClue::None => (),
                MasyuClue::White => board.push(Item::cell(y, x, "black", ItemKind::Circle)),
                MasyuClue::Black => board.push(Item::cell(y, x, "black", ItemKind::FilledCircle)),
            }
        }
    }

    board.add_lines_irrefutable_facts(&is_line, "green", None);

    Ok(board)
}

#[cfg(test)]
mod tests {
    use super::solve;
    use crate::board::*;
    use crate::compare_board;
    use crate::uniqueness::Uniqueness;

    #[test]
    #[rustfmt::skip]
    fn test_solve() {
        compare_board!(
            solve("https://puzz.link/p?masyu/10/10/0600003i06b1300600000a30600i090330"),
            Board {
                kind: BoardKind::Grid,
                height: 10,
                width: 10,
                data: vec![
                    Item { y: 1, x: 9, color: "black", kind: ItemKind::FilledCircle },
                    Item { y: 3, x: 19, color: "black", kind: ItemKind::Circle },
                    Item { y: 5, x: 3, color: "black", kind: ItemKind::FilledCircle },
                    Item { y: 5, x: 17, color: "black", kind: ItemKind::FilledCircle },
                    Item { y: 7, x: 1, color: "black", kind: ItemKind::Circle },
                    Item { y: 7, x: 5, color: "black", kind: ItemKind::FilledCircle },
                    Item { y: 7, x: 11, color: "black", kind: ItemKind::Circle },
                    Item { y: 7, x: 15, color: "black", kind: ItemKind::Circle },
                    Item { y: 9, x: 13, color: "black", kind: ItemKind::FilledCircle },
                    Item { y: 13, x: 7, color: "black", kind: ItemKind::Circle },
                    Item { y: 13, x: 11, color: "black", kind: ItemKind::Circle },
                    Item { y: 13, x: 15, color: "black", kind: ItemKind::Circle },
                    Item { y: 15, x: 7, color: "black", kind: ItemKind::FilledCircle },
                    Item { y: 17, x: 3, color: "black", kind: ItemKind::FilledCircle },
                    Item { y: 17, x: 15, color: "black", kind: ItemKind::Circle },
                    Item { y: 19, x: 9, color: "black", kind: ItemKind::Circle },
                    Item { y: 19, x: 15, color: "black", kind: ItemKind::Circle },
                    Item { y: 2, x: 1, color: "green", kind: ItemKind::Line },
                    Item { y: 2, x: 3, color: "green", kind: ItemKind::Line },
                    Item { y: 2, x: 5, color: "green", kind: ItemKind::Line },
                    Item { y: 2, x: 7, color: "green", kind: ItemKind::Cross },
                    Item { y: 2, x: 9, color: "green", kind: ItemKind::Line },
                    Item { y: 2, x: 11, color: "green", kind: ItemKind::Cross },
                    Item { y: 2, x: 13, color: "green", kind: ItemKind::Cross },
                    Item { y: 2, x: 15, color: "green", kind: ItemKind::Cross },
                    Item { y: 2, x: 17, color: "green", kind: ItemKind::Line },
                    Item { y: 2, x: 19, color: "green", kind: ItemKind::Line },
                    Item { y: 4, x: 1, color: "green", kind: ItemKind::Line },
                    Item { y: 4, x: 3, color: "green", kind: ItemKind::Line },
                    Item { y: 4, x: 5, color: "green", kind: ItemKind::Cross },
                    Item { y: 4, x: 7, color: "green", kind: ItemKind::Line },
                    Item { y: 4, x: 9, color: "green", kind: ItemKind::Line },
                    Item { y: 4, x: 11, color: "green", kind: ItemKind::Cross },
                    Item { y: 4, x: 13, color: "green", kind: ItemKind::Cross },
                    Item { y: 4, x: 15, color: "green", kind: ItemKind::Cross },
                    Item { y: 4, x: 17, color: "green", kind: ItemKind::Line },
                    Item { y: 4, x: 19, color: "green", kind: ItemKind::Line },
                    Item { y: 6, x: 1, color: "green", kind: ItemKind::Line },
                    Item { y: 6, x: 3, color: "green", kind: ItemKind::Cross },
                    Item { y: 6, x: 5, color: "green", kind: ItemKind::Cross },
                    Item { y: 6, x: 7, color: "green", kind: ItemKind::Cross },
                    Item { y: 6, x: 9, color: "green", kind: ItemKind::Cross },
                    Item { y: 6, x: 11, color: "green", kind: ItemKind::Line },
                    Item { y: 6, x: 13, color: "green", kind: ItemKind::Line },
                    Item { y: 6, x: 15, color: "green", kind: ItemKind::Cross },
                    Item { y: 6, x: 17, color: "green", kind: ItemKind::Cross },
                    Item { y: 6, x: 19, color: "green", kind: ItemKind::Line },
                    Item { y: 8, x: 1, color: "green", kind: ItemKind::Line },
                    Item { y: 8, x: 3, color: "green", kind: ItemKind::Cross },
                    Item { y: 8, x: 5, color: "green", kind: ItemKind::Line },
                    Item { y: 8, x: 7, color: "green", kind: ItemKind::Cross },
                    Item { y: 8, x: 9, color: "green", kind: ItemKind::Line },
                    Item { y: 8, x: 11, color: "green", kind: ItemKind::Line },
                    Item { y: 8, x: 13, color: "green", kind: ItemKind::Cross },
                    Item { y: 8, x: 15, color: "green", kind: ItemKind::Cross },
                    Item { y: 8, x: 17, color: "green", kind: ItemKind::Line },
                    Item { y: 8, x: 19, color: "green", kind: ItemKind::Line },
                    Item { y: 10, x: 1, color: "green", kind: ItemKind::Cross },
                    Item { y: 10, x: 3, color: "green", kind: ItemKind::Line },
                    Item { y: 10, x: 5, color: "green", kind: ItemKind::Line },
                    Item { y: 10, x: 7, color: "green", kind: ItemKind::Line },
                    Item { y: 10, x: 9, color: "green", kind: ItemKind::Cross },
                    Item { y: 10, x: 11, color: "green", kind: ItemKind::Line },
                    Item { y: 10, x: 13, color: "green", kind: ItemKind::Line },
                    Item { y: 10, x: 15, color: "green", kind: ItemKind::Cross },
                    Item { y: 10, x: 17, color: "green", kind: ItemKind::Cross },
                    Item { y: 10, x: 19, color: "green", kind: ItemKind::Line },
                    Item { y: 12, x: 1, color: "green", kind: ItemKind::Line },
                    Item { y: 12, x: 3, color: "green", kind: ItemKind::Cross },
                    Item { y: 12, x: 5, color: "green", kind: ItemKind::Line },
                    Item { y: 12, x: 7, color: "green", kind: ItemKind::Line },
                    Item { y: 12, x: 9, color: "green", kind: ItemKind::Line },
                    Item { y: 12, x: 11, color: "green", kind: ItemKind::Cross },
                    Item { y: 12, x: 13, color: "green", kind: ItemKind::Line },
                    Item { y: 12, x: 15, color: "green", kind: ItemKind::Line },
                    Item { y: 12, x: 17, color: "green", kind: ItemKind::Line },
                    Item { y: 12, x: 19, color: "green", kind: ItemKind::Line },
                    Item { y: 14, x: 1, color: "green", kind: ItemKind::Line },
                    Item { y: 14, x: 3, color: "green", kind: ItemKind::Line },
                    Item { y: 14, x: 5, color: "green", kind: ItemKind::Cross },
                    Item { y: 14, x: 7, color: "green", kind: ItemKind::Line },
                    Item { y: 14, x: 9, color: "green", kind: ItemKind::Cross },
                    Item { y: 14, x: 11, color: "green", kind: ItemKind::Cross },
                    Item { y: 14, x: 13, color: "green", kind: ItemKind::Cross },
                    Item { y: 14, x: 15, color: "green", kind: ItemKind::Line },
                    Item { y: 14, x: 17, color: "green", kind: ItemKind::Line },
                    Item { y: 14, x: 19, color: "green", kind: ItemKind::Line },
                    Item { y: 16, x: 1, color: "green", kind: ItemKind::Line },
                    Item { y: 16, x: 3, color: "green", kind: ItemKind::Line },
                    Item { y: 16, x: 5, color: "green", kind: ItemKind::Cross },
                    Item { y: 16, x: 7, color: "green", kind: ItemKind::Cross },
                    Item { y: 16, x: 9, color: "green", kind: ItemKind::Cross },
                    Item { y: 16, x: 11, color: "green", kind: ItemKind::Cross },
                    Item { y: 16, x: 13, color: "green", kind: ItemKind::Cross },
                    Item { y: 16, x: 15, color: "green", kind: ItemKind::Cross },
                    Item { y: 16, x: 17, color: "green", kind: ItemKind::Line },
                    Item { y: 16, x: 19, color: "green", kind: ItemKind::Line },
                    Item { y: 18, x: 1, color: "green", kind: ItemKind::Line },
                    Item { y: 18, x: 3, color: "green", kind: ItemKind::Cross },
                    Item { y: 18, x: 5, color: "green", kind: ItemKind::Cross },
                    Item { y: 18, x: 7, color: "green", kind: ItemKind::Cross },
                    Item { y: 18, x: 9, color: "green", kind: ItemKind::Cross },
                    Item { y: 18, x: 11, color: "green", kind: ItemKind::Line },
                    Item { y: 18, x: 13, color: "green", kind: ItemKind::Line },
                    Item { y: 18, x: 15, color: "green", kind: ItemKind::Cross },
                    Item { y: 18, x: 17, color: "green", kind: ItemKind::Cross },
                    Item { y: 18, x: 19, color: "green", kind: ItemKind::Line },
                    Item { y: 1, x: 2, color: "green", kind: ItemKind::Line },
                    Item { y: 1, x: 4, color: "green", kind: ItemKind::Cross },
                    Item { y: 1, x: 6, color: "green", kind: ItemKind::Line },
                    Item { y: 1, x: 8, color: "green", kind: ItemKind::Line },
                    Item { y: 1, x: 10, color: "green", kind: ItemKind::Cross },
                    Item { y: 1, x: 12, color: "green", kind: ItemKind::Cross },
                    Item { y: 1, x: 14, color: "green", kind: ItemKind::Cross },
                    Item { y: 1, x: 16, color: "green", kind: ItemKind::Cross },
                    Item { y: 1, x: 18, color: "green", kind: ItemKind::Line },
                    Item { y: 3, x: 2, color: "green", kind: ItemKind::Cross },
                    Item { y: 3, x: 4, color: "green", kind: ItemKind::Cross },
                    Item { y: 3, x: 6, color: "green", kind: ItemKind::Line },
                    Item { y: 3, x: 8, color: "green", kind: ItemKind::Cross },
                    Item { y: 3, x: 10, color: "green", kind: ItemKind::Cross },
                    Item { y: 3, x: 12, color: "green", kind: ItemKind::Cross },
                    Item { y: 3, x: 14, color: "green", kind: ItemKind::Cross },
                    Item { y: 3, x: 16, color: "green", kind: ItemKind::Cross },
                    Item { y: 3, x: 18, color: "green", kind: ItemKind::Cross },
                    Item { y: 5, x: 2, color: "green", kind: ItemKind::Cross },
                    Item { y: 5, x: 4, color: "green", kind: ItemKind::Line },
                    Item { y: 5, x: 6, color: "green", kind: ItemKind::Line },
                    Item { y: 5, x: 8, color: "green", kind: ItemKind::Cross },
                    Item { y: 5, x: 10, color: "green", kind: ItemKind::Line },
                    Item { y: 5, x: 12, color: "green", kind: ItemKind::Cross },
                    Item { y: 5, x: 14, color: "green", kind: ItemKind::Line },
                    Item { y: 5, x: 16, color: "green", kind: ItemKind::Line },
                    Item { y: 5, x: 18, color: "green", kind: ItemKind::Cross },
                    Item { y: 7, x: 2, color: "green", kind: ItemKind::Cross },
                    Item { y: 7, x: 4, color: "green", kind: ItemKind::Cross },
                    Item { y: 7, x: 6, color: "green", kind: ItemKind::Line },
                    Item { y: 7, x: 8, color: "green", kind: ItemKind::Line },
                    Item { y: 7, x: 10, color: "green", kind: ItemKind::Cross },
                    Item { y: 7, x: 12, color: "green", kind: ItemKind::Cross },
                    Item { y: 7, x: 14, color: "green", kind: ItemKind::Line },
                    Item { y: 7, x: 16, color: "green", kind: ItemKind::Line },
                    Item { y: 7, x: 18, color: "green", kind: ItemKind::Cross },
                    Item { y: 9, x: 2, color: "green", kind: ItemKind::Line },
                    Item { y: 9, x: 4, color: "green", kind: ItemKind::Cross },
                    Item { y: 9, x: 6, color: "green", kind: ItemKind::Cross },
                    Item { y: 9, x: 8, color: "green", kind: ItemKind::Line },
                    Item { y: 9, x: 10, color: "green", kind: ItemKind::Cross },
                    Item { y: 9, x: 12, color: "green", kind: ItemKind::Cross },
                    Item { y: 9, x: 14, color: "green", kind: ItemKind::Line },
                    Item { y: 9, x: 16, color: "green", kind: ItemKind::Line },
                    Item { y: 9, x: 18, color: "green", kind: ItemKind::Cross },
                    Item { y: 11, x: 2, color: "green", kind: ItemKind::Line },
                    Item { y: 11, x: 4, color: "green", kind: ItemKind::Cross },
                    Item { y: 11, x: 6, color: "green", kind: ItemKind::Cross },
                    Item { y: 11, x: 8, color: "green", kind: ItemKind::Cross },
                    Item { y: 11, x: 10, color: "green", kind: ItemKind::Line },
                    Item { y: 11, x: 12, color: "green", kind: ItemKind::Cross },
                    Item { y: 11, x: 14, color: "green", kind: ItemKind::Cross },
                    Item { y: 11, x: 16, color: "green", kind: ItemKind::Line },
                    Item { y: 11, x: 18, color: "green", kind: ItemKind::Cross },
                    Item { y: 13, x: 2, color: "green", kind: ItemKind::Cross },
                    Item { y: 13, x: 4, color: "green", kind: ItemKind::Line },
                    Item { y: 13, x: 6, color: "green", kind: ItemKind::Cross },
                    Item { y: 13, x: 8, color: "green", kind: ItemKind::Cross },
                    Item { y: 13, x: 10, color: "green", kind: ItemKind::Line },
                    Item { y: 13, x: 12, color: "green", kind: ItemKind::Line },
                    Item { y: 13, x: 14, color: "green", kind: ItemKind::Cross },
                    Item { y: 13, x: 16, color: "green", kind: ItemKind::Cross },
                    Item { y: 13, x: 18, color: "green", kind: ItemKind::Cross },
                    Item { y: 15, x: 2, color: "green", kind: ItemKind::Cross },
                    Item { y: 15, x: 4, color: "green", kind: ItemKind::Cross },
                    Item { y: 15, x: 6, color: "green", kind: ItemKind::Cross },
                    Item { y: 15, x: 8, color: "green", kind: ItemKind::Line },
                    Item { y: 15, x: 10, color: "green", kind: ItemKind::Line },
                    Item { y: 15, x: 12, color: "green", kind: ItemKind::Line },
                    Item { y: 15, x: 14, color: "green", kind: ItemKind::Line },
                    Item { y: 15, x: 16, color: "green", kind: ItemKind::Cross },
                    Item { y: 15, x: 18, color: "green", kind: ItemKind::Cross },
                    Item { y: 17, x: 2, color: "green", kind: ItemKind::Cross },
                    Item { y: 17, x: 4, color: "green", kind: ItemKind::Line },
                    Item { y: 17, x: 6, color: "green", kind: ItemKind::Line },
                    Item { y: 17, x: 8, color: "green", kind: ItemKind::Line },
                    Item { y: 17, x: 10, color: "green", kind: ItemKind::Line },
                    Item { y: 17, x: 12, color: "green", kind: ItemKind::Cross },
                    Item { y: 17, x: 14, color: "green", kind: ItemKind::Line },
                    Item { y: 17, x: 16, color: "green", kind: ItemKind::Line },
                    Item { y: 17, x: 18, color: "green", kind: ItemKind::Cross },
                    Item { y: 19, x: 2, color: "green", kind: ItemKind::Line },
                    Item { y: 19, x: 4, color: "green", kind: ItemKind::Line },
                    Item { y: 19, x: 6, color: "green", kind: ItemKind::Line },
                    Item { y: 19, x: 8, color: "green", kind: ItemKind::Line },
                    Item { y: 19, x: 10, color: "green", kind: ItemKind::Line },
                    Item { y: 19, x: 12, color: "green", kind: ItemKind::Cross },
                    Item { y: 19, x: 14, color: "green", kind: ItemKind::Line },
                    Item { y: 19, x: 16, color: "green", kind: ItemKind::Line },
                    Item { y: 19, x: 18, color: "green", kind: ItemKind::Line },
                ],
                uniqueness: Uniqueness::Unique,
            },
        );
    }
}
