use crate::util;
use cspuz_rs::graph;
use cspuz_rs::serializer::{
    problem_to_url_with_context_and_site, url_to_problem, Choice, Combinator, Context,
    ContextBasedGrid, MultiDigit, Size, SizeDoubler, Spaces,
};
use cspuz_rs::solver::Solver;

pub fn solve_kurarin(
    clues: &[Vec<i32>],
) -> Option<(graph::BoolGridEdgesIrrefutableFacts, Vec<Vec<Option<bool>>>)> {
    let (h, w) = util::infer_shape(clues);
    let h = (h + 1) / 2;
    let w = (w + 1) / 2;

    let mut solver = Solver::new();
    let is_black = &solver.bool_var_2d((h, w));
    solver.add_answer_key_bool(is_black);

    let is_line = &graph::BoolGridEdges::new(&mut solver, (h - 1, w - 1));
    solver.add_answer_key_bool(&is_line.horizontal);
    solver.add_answer_key_bool(&is_line.vertical);

    let is_passed = &graph::single_cycle_grid_edges(&mut solver, is_line);
    solver.add_expr(is_black ^ is_passed);

    for y in 0..(h * 2 - 1) {
        for x in 0..(w * 2 - 1) {
            let clue = clues[y][x];
            if clue == 0 {
                continue;
            }

            let num_neighbors = (if y % 2 == 0 { 1 } else { 2 }) * (if x % 2 == 0 { 1 } else { 2 });
            let num_black = is_black
                .slice(((y / 2)..=((y + 1) / 2), (x / 2)..=((x + 1) / 2)))
                .count_true();

            if clue == 1 {
                if num_neighbors == 1 || num_neighbors == 2 {
                    solver.add_expr(num_black.eq(num_neighbors));
                } else {
                    solver.add_expr(num_black.ge(3));
                }
            } else if clue == 2 {
                if num_neighbors == 1 {
                    return None;
                } else {
                    solver.add_expr(num_black.eq(num_neighbors / 2));
                }
            } else if clue == 3 {
                if num_neighbors == 1 || num_neighbors == 2 {
                    solver.add_expr(num_black.eq(0));
                } else {
                    solver.add_expr(num_black.le(1));
                }
            }
        }
    }

    solver
        .irrefutable_facts()
        .map(|f| (f.get(is_line), f.get(is_black)))
}

type Problem = Vec<Vec<i32>>;

fn combinator() -> impl Combinator<Problem> {
    Size::new(SizeDoubler::new(ContextBasedGrid::new(Choice::new(vec![
        Box::new(Spaces::new_with_repetition(0, 'g', 2)),
        Box::new(MultiDigit::new(4, 2)),
    ]))))
}

pub fn serialize_problem(problem: &Problem) -> Option<String> {
    let (h, w) = util::infer_shape(problem);
    problem_to_url_with_context_and_site(
        combinator(),
        "kurarin",
        "https://pzprxs.vercel.app/p?",
        problem.clone(),
        &Context::sized((h + 1) / 2, (w + 1) / 2),
    )
}

pub fn deserialize_problem(url: &str) -> Option<Problem> {
    // TODO: the url generated by editor ignores the dot on the most bottom-right cell.
    // So we append "g" here to make it work.
    let url = url.to_owned() + "g";
    url_to_problem(combinator(), &["kurarin"], &url)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn problem_for_tests() -> Problem {
        vec![
            vec![0, 2, 0, 0, 0, 0, 0, 0, 3, 0, 0],
            vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            vec![0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
            vec![0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1],
            vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            vec![0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0],
            vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            vec![0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
            vec![0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
        ]
    }

    #[test]
    fn test_kurarin_problem() {
        let problem = problem_for_tests();
        let ans = solve_kurarin(&problem);
        assert!(ans.is_some());

        let ans = ans.unwrap();
        let expected = (
            graph::BoolGridEdgesIrrefutableFacts {
                horizontal: crate::util::tests::to_option_bool_2d([
                    [0, 1, 1, 1, 0],
                    [1, 0, 0, 1, 0],
                    [1, 1, 0, 1, 0],
                    [0, 0, 1, 0, 1],
                    [0, 0, 0, 1, 1],
                ]),
                vertical: crate::util::tests::to_option_bool_2d([
                    [0, 1, 0, 0, 1, 0],
                    [1, 0, 0, 1, 0, 0],
                    [0, 0, 1, 0, 1, 0],
                    [0, 0, 0, 1, 0, 1],
                ]),
            },
            crate::util::tests::to_option_bool_2d([
                [1, 0, 0, 0, 0, 1],
                [0, 0, 1, 0, 0, 1],
                [0, 0, 0, 0, 0, 1],
                [1, 1, 0, 0, 0, 0],
                [1, 1, 1, 0, 0, 0],
            ]),
        );
        assert_eq!(ans, expected);
    }

    #[test]
    fn test_kurarin_serializer() {
        let problem = problem_for_tests();
        let url = "https://pzprxs.vercel.app/p?kurarin/6/5/2icn4kcg1l8icm4l3g";

        // TODO: the url generated by editor ignores the dot on the most bottom-right cell.
        // We cannot serialize to the same url yet.
        assert_eq!(deserialize_problem(url), Some(problem));
    }
}
